### ISSUE TITLE
Block names after planning failure?

### ISSUE THREAD

**Issue by aaronjoh** [personalrobotics/block_sorting#9]
I'm having trouble getting the demo to run, but one thing I have noticed is if CBiRRT fails (and therefore we can assume other planners have failed) I get an error that "body b1 does not have unique name". How do we assign these names?

I would guess that turning down the timeout on CBiRRT would make this happen more often.

```
aaronjoh@johnson:~/sc-ros/src/block_sorting/scripts$ python run_demo.py --perception-sim --viewer rviz
[WARNING] [root:logger.py:71]:initialize_logging: Install termcolor to colorize log messages.
[ WARN] [1442347315.772727123]: Group 'head_hand' is empty.
[kinbody.cpp:1470 SetDOFValues] dof 4 value is not in limits 0.000000e+00<5.235988e-01
[kinbody.cpp:1470 SetDOFValues] dof 15 value is not in limits 0.000000e+00<5.235988e-01
WARNING: QApplication was not created in the main() thread.
[ INFO] [1442347317.637288437]: Stereo is NOT SUPPORTED
[ INFO] [1442347317.637482848]: OpenGl version: 3 (GLSL 1.3).
[EnvironmentDisplay.cpp:156 EnvironmentChangeSlot] Attempted to switch to environment with non-existent ID 0.
Redecting objects
[INFO] [block_sorting:run_demo.py:97]:<module>: Redecting objects
Press enter to continue, r to redetect
The block name b2  of color ( (0.0, 0.0, 255.0) ) belongs in the  blue bin (idx= 1 )

Grabbing block b2
[INFO] [block_sorting:run_demo.py:120]:<module>: Grabbing block b2
[openravepy_robot.cpp:880 GetActiveManipulatorIndex] GetActiveManipulatorIndex is deprecated
[INFO] [prpy.planning.base:base.py:239]:plan: Sequence - Calling planner "TSRPlanner(Sequence(SnapPlanner, VectorFieldPlanner, GreedyIKPlanner, Trajopt))".
[INFO] [prpy.planning.base:base.py:239]:plan: Sequence - Calling planner "SnapPlanner".
[WARNING] [prpy.planning.base:base.py:257]:plan: Planning with SnapPlanner failed: Straight line trajectory is not valid.
[INFO] [prpy.planning.base:base.py:239]:plan: Sequence - Calling planner "Trajopt".
[WARNING] [prpy.planning.base:base.py:257]:plan: Planning with Trajopt failed: Result was in collision.
[WARNING] [prpy.planning.tsr:tsr.py:176]:PlanToTSR: Planning to IK solution set 1 of 3 failed: All planners failed.
[INFO] [prpy.planning.base:base.py:239]:plan: Sequence - Calling planner "SnapPlanner".
[WARNING] [prpy.planning.base:base.py:257]:plan: Planning with SnapPlanner failed: Straight line trajectory is not valid.
[INFO] [prpy.planning.base:base.py:239]:plan: Sequence - Calling planner "Trajopt".
[WARNING] [prpy.planning.base:base.py:257]:plan: Planning with Trajopt failed: Result was in collision.
[WARNING] [prpy.planning.tsr:tsr.py:176]:PlanToTSR: Planning to IK solution set 2 of 3 failed: All planners failed.
[INFO] [prpy.planning.base:base.py:239]:plan: Sequence - Calling planner "SnapPlanner".
[WARNING] [prpy.planning.base:base.py:257]:plan: Planning with SnapPlanner failed: Straight line trajectory is not valid.
[INFO] [prpy.planning.base:base.py:239]:plan: Sequence - Calling planner "Trajopt".
[WARNING] [prpy.planning.base:base.py:257]:plan: Planning with Trajopt failed: Result was in collision.
[WARNING] [prpy.planning.tsr:tsr.py:176]:PlanToTSR: Planning to IK solution set 3 of 3 failed: All planners failed.
[WARNING] [prpy.planning.base:base.py:257]:plan: Planning with TSRPlanner(Sequence(SnapPlanner, VectorFieldPlanner, GreedyIKPlanner, Trajopt)) failed: Planning to the top 3 of 273 IK solution sets failed.
[INFO] [prpy.planning.base:base.py:239]:plan: Sequence - Calling planner "CBiRRT".
[GeneralIK.cpp:58 Init] Initializing GeneralIK Solver
[cbirrtproblem.cpp:112 main] IKsolver initialized
[cbirrtproblem.cpp:771 RunCBirrt] Doing Goal sampling
[cbirrtproblem.cpp:843 RunCBirrt] Setting default init config to current config
[GeneralIK.cpp:58 Init] Initializing GeneralIK Solver
[cbirrt.cpp:260 InitPlan] numdofs: 7
[cbirrt.cpp:305 InitPlan] grabbed: 0
[GeneralIK.cpp:58 Init] Initializing GeneralIK Solver
[cbirrt.cpp:314 InitPlan] Psample: 0.100000
[cbirrt.cpp:392 InitPlan] Checking for start projection...
[cbirrt.cpp:427 InitPlan] Start Node(s) Created
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:623 PlanPath] Got first goal ik solution!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:861 AddRootConfiguration] Attached Solver Found a Solution!
[cbirrt.cpp:947 AddRootConfiguration] Constrained IK solution(s) found!
[cbirrt.cpp:717 PlanPath] Planner Failed: 25.000000s time limit reached
[WARNING] [prpy.planning.base:base.py:257]:plan: Planning with CBiRRT failed: Unknown error: 0 Planner Failed: 25s time limit reached

Failed to grab block
[ERROR] [block_sorting:run_demo.py:131]:<module>: Failed to grab block
[INFO] [prpy.planning.base:base.py:239]:plan: Sequence - Calling planner "SnapPlanner".
[WARNING] [prpy.planning.base:base.py:257]:plan: Planning with SnapPlanner failed: Straight line trajectory is not valid.
[INFO] [prpy.planning.base:base.py:239]:plan: Sequence - Calling planner "Trajopt".
[INFO] [prpy.planning.base:base.py:248]:plan: Sequence - Planning succeeded after 1.757 seconds with "Trajopt".
[INFO] [prpy.base.robot:robot.py:393]:do_execute: Post-processing path with 10 waypoints.
[ParabolicSmoother.cpp:360 PlanPath] Terminated after 2 iterations and 1.048726 seconds.
[INFO] [prpy.base.robot:robot.py:403]:do_execute: Post-processing took 1.341 seconds and produced a path with 16 waypoints and a duration of 3.257 seconds.
Redecting objects
[INFO] [block_sorting:run_demo.py:97]:<module>: Redecting objects
Traceback (most recent call last):
  File "run_demo.py", line 100, in <module>
    blocks = perception_simulator.DetectBlocks(robot, table, blocks=[])
  File "/home/aaronjoh/sc-ros/src/prpy/src/prpy/perception/base.py", line 11, in __call__
    return self.func(instance, robot, *args, **kw_args)
  File "/home/aaronjoh/sc-ros/src/block_sorting/src/block_sorting/perception_simulator.py", line 82, in DetectBlocks
    env.Add(block)
openravepy._openravepy_.openravepy_ext.openrave_exception: openrave (Failed): env=1, body b1 does not have unique name
[INFO] [rospy.core:core.py:387]:signal_shutdown: signal_shutdown [atexit]
```

**Comment by mkoval** [comment]
Confirmed. I get the same error when I run the demo.

@Shushman Can you look into this?

**Comment by mklingen** [comment]
AFAIK we just generated a random number for the blocks, but perhaps its not random enough!

**Comment by mklingen** [comment]
IMO the solution is to delete the existing blocks before re-perceiving. ie

```
        for block in blocks:
            env.RemoveKinBody(block);
```

**Comment by mklingen** [comment]
https://github.com/personalrobotics/block_sorting/pull/13
